import type { Recipe } from '@/types';

export const mockRecipes: Recipe[] = [
  {
    id: 'rec_001',
    slug: 'test-soup',
    title: { es: 'Sopa de test', en: 'Test Soup' },
    description: { es: 'Una sopa', en: 'A soup' },
    image: '',
    category: 'soups',
    tags: ['quick'],
    difficulty: 'easy',
    totalTime: 30,
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    thermomixModel: ['TM5', 'TM6'],
    accessories: [],
    ingredients: [{ id: 'i1', name: { es: 'Agua', en: 'Water' }, amount: 500, unit: 'ml', optional: false }],
    steps: [{ id: 's1', order: 1, instruction: { es: 'Hervir', en: 'Boil' } }],
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
  },
  {
    id: 'rec_002',
    slug: 'test-bread',
    title: { es: 'Pan de test', en: 'Test Bread' },
    description: { es: 'Un pan', en: 'A bread' },
    image: '',
    category: 'breads',
    tags: ['classic'],
    difficulty: 'medium',
    totalTime: 60,
    prepTime: 15,
    cookTime: 45,
    servings: 6,
    thermomixModel: ['TM5'],
    accessories: [],
    ingredients: [],
    steps: [],
    createdAt: '2026-01-02',
    updatedAt: '2026-01-02',
  },
  {
    id: 'rec_003',
    slug: 'test-dessert',
    title: { es: 'Postre de test', en: 'Test Dessert' },
    description: { es: 'Un postre', en: 'A dessert' },
    image: '',
    category: 'desserts',
    tags: ['sweet'],
    difficulty: 'hard',
    totalTime: 90,
    prepTime: 30,
    cookTime: 60,
    servings: 8,
    thermomixModel: ['TM6'],
    accessories: ['varoma'],
    ingredients: [],
    steps: [],
    createdAt: '2026-01-03',
    updatedAt: '2026-01-03',
  },
];
